export const fallbackProducts = [
  {
    id: "fallback-1",
    slug: "brad-v1-custom",
    name: "Brad V1 Custom",
    category: "Kemeja Custom",
    base_price: 185000,
    thumbnail_url: "/assets/katalog/Model Kemeja/Brad-v1/(brad v-1)hitam.png",
    canvas_config: {
      color: "#111827",
      label: "Brad V1",
    },
  },
  {
    id: "fallback-2",
    slug: "brad-v2-custom",
    name: "Brad V2 Custom",
    category: "Kemeja Custom",
    base_price: 215000,
    thumbnail_url: "/assets/katalog/Model Kemeja/Brad-v2/(brad v-2)warna hitam.png",
    canvas_config: {
      color: "#1e3a8a",
      label: "Brad V2",
    },
  },
  {
    id: "fallback-3",
    slug: "brad-v3-custom",
    name: "Brad V3 Custom",
    category: "Kemeja Custom",
    base_price: 235000,
    thumbnail_url: "/assets/katalog/Model Kemeja/Brad-V3/(brad v-3)hitam.png",
    canvas_config: {
      color: "#0f172a",
      label: "Brad V3",
    },
  },
  {
    id: "fallback-4",
    slug: "jaket-custom",
    name: "Jaket Custom",
    category: "Jaket",
    base_price: 285000,
    thumbnail_url: "/assets/katalog/jaket/jaket-depan-hitam.jpeg",
    canvas_config: {
      color: "#18181b",
      label: "Jaket",
    },
  },
  {
    id: "fallback-5",
    slug: "rompi-tactical-custom",
    name: "Tactical Vest Custom",
    category: "Rompi",
    base_price: 265000,
    thumbnail_url: "/assets/katalog/Rompi/Tactical Vest/Vest-hitam.jpeg",
    canvas_config: { color: "#111827", label: "Rompi Tactical" },
  },
  {
    id: "fallback-6",
    slug: "warrior-custom",
    name: "Warrior Custom",
    category: "Celana",
    base_price: 245000,
    thumbnail_url: "/assets/katalog/Celana/Warrior/warior-depan-hitam.jpeg",
    canvas_config: { color: "#1f2937", label: "Celana Warrior" },
  },
  {
    id: "fallback-7",
    slug: "polo-custom",
    name: "Polo Custom",
    category: "Polo",
    base_price: 175000,
    thumbnail_url: "/assets/katalog/Polo shirt/Kaospolo-hitam.png",
    canvas_config: { color: "#111827", label: "Polo" },
  },
];
